version: '3.8'

services:

  rdvroum_nginx:
    container_name: rdvroum_nginx
    image: nginx:1.27
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/errors.conf:/etc/nginx/errors.conf:ro
      - ./nginx/html:/usr/share/nginx/html
    links:
      - rdvroum_php
    depends_on:
      - rdvroum_php
    networks:
      - rdvroum_network

  rdvroum_php:
    container_name: rdvroum_php
    restart: unless-stopped
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: "mysql://root:rdvroum_root_password@rdvroum_mysql:3306/rdvroum_db"
    depends_on:
      - rdvroum_mysql
    ports:
      - "9001:9000"
    networks:
      - rdvroum_network

  rdvroum_mysql:
    container_name: rdvroum_mysql
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - rdvroum_network

  rdvroum_mailhog:
    container_name: rdvroum_mailhog
    image: mailhog/mailhog
    ports:
      - "1027:1025"
      - "8025:8025"
    networks:
      - rdvroum_network

networks:
  rdvroum_network:
    external:
      name: rdvroum_network
volumes:
  data: